### ISSUE TITLE
What's the django version for this app?

### ISSUE THREAD

**Issue by tolerious** [MSA-Argentina/django-bootstrap-markdown#2]
It seems that syncdb not used in django 1.7 and higher, so what's the django version you use?

**Comment by DoctorMalboro** [comment]
Hello,

I'm using Django 1.6.10 in production but I've tested in Django 1.7.7 and Django 1.8 in Python 2 and 3 and they work perfectly. Hope this clears out any doubt.

In any case, I will clear this up in the readme. Thank you!
